- id: '1765060726911'
  alias: CO2 800 lcrelay 1 on
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - number.birb_7fb0d8_co2_display
    above: 800
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.aquarium_8a23d8_relay_1
  mode: single
- id: '1765061147628'
  alias: CO2 UV lcrelay 1
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - number.birb_7fb0d8_co2_display
    below: 700
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.aquarium_8a23d8_relay_1
  mode: single
